name: Deploy static site to Cloudflare Pages

on:
  push:
    branches:
      - main  # deploy when main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        accountId: ${{ secrets.CF_ACCOUNT_ID }}
        projectName: hicons    # your Pages project name
        directory: ./public    # folder to deploy
